#pragma once

#include <QDir>
#include <QFileInfo>
#include <QString>

namespace remustwo::test {

inline QString sourceDir() {
    return QStringLiteral(REMUSTWO_SOURCE_DIR);
}

/// Tiny generated bytes that match testdata/fixture.dat. Not a game dump.
inline QString syntheticFixtureDat() {
    return sourceDir() + QStringLiteral("/testdata/fixture.dat");
}

inline QString syntheticFixtureRom() {
    return sourceDir() + QStringLiteral("/testdata/fixture.bin");
}

/// Local copyrighted dumps. Gitignored. Never read this from CI as a required path.
inline QString testRomsDir() {
    return sourceDir() + QStringLiteral("/testroms");
}

inline bool hasLocalTestRoms() {
    const QDir dir(testRomsDir());
    if (!dir.exists())
        return false;
    for (const QFileInfo &info : dir.entryInfoList(QDir::Files | QDir::NoDotAndDotDot)) {
        if (info.fileName().compare(QStringLiteral("README.md"), Qt::CaseInsensitive) == 0)
            continue;
        if (info.size() > 0)
            return true;
    }
    return false;
}

} // namespace remustwo::test
