#ifndef REMUSTWO_LOGGING_CATEGORIES_H
#define REMUSTWO_LOGGING_CATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCore)
Q_DECLARE_LOGGING_CATEGORY(logMetadata)
Q_DECLARE_LOGGING_CATEGORY(logCli)

#endif // REMUSTWO_LOGGING_CATEGORIES_H
