#include "constants/systems.h"

namespace remustwo {
namespace Constants {
namespace Systems {

const QMap<int, QStringList> &systemDbExtensions() {
    static const QMap<int, QStringList> kExtensions = {
        { ID_NES, { QStringLiteral(".nes"), QStringLiteral(".nez"), QStringLiteral(".unf"), QStringLiteral(".unif") } },
        { ID_FDS, { QStringLiteral(".fds") } },
        { ID_MASTER_SYSTEM, { QStringLiteral(".sms") } },
        { ID_ATARI_2600, { QStringLiteral(".a26"), QStringLiteral(".bin") } },
        { ID_ATARI_5200, { QStringLiteral(".a52"), QStringLiteral(".bin"), QStringLiteral(".car") } },
        { ID_ATARI_8BIT, { QStringLiteral(".atr"), QStringLiteral(".xex"), QStringLiteral(".xfd"), QStringLiteral(".atx"), QStringLiteral(".car"), QStringLiteral(".bin") } },
        { ID_ATARI_ST, { QStringLiteral(".st"), QStringLiteral(".msa"), QStringLiteral(".stx"), QStringLiteral(".dim"), QStringLiteral(".img") } },
        { ID_ATARI_JAGUAR_CD, { QStringLiteral(".j64"), QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".chd") } },
        { ID_ATARI_7800, { QStringLiteral(".a78") } },
        { ID_SNES, { QStringLiteral(".sfc"), QStringLiteral(".smc") } },
        { ID_GENESIS, { QStringLiteral(".md"), QStringLiteral(".gen"), QStringLiteral(".smd"), QStringLiteral(".32x"), QStringLiteral(".68k") } },
        { ID_TURBOGRAFX16, { QStringLiteral(".pce") } },
        { ID_GB, { QStringLiteral(".gb") } },
        { ID_PSX, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso"), QStringLiteral(".img"), QStringLiteral(".pbp"), QStringLiteral(".chd"), QStringLiteral(".mdf"), QStringLiteral(".mds"), QStringLiteral(".ecm"), QStringLiteral(".ccd"), QStringLiteral(".sub"), QStringLiteral(".m3u") } },
        { ID_N64, { QStringLiteral(".n64"), QStringLiteral(".z64"), QStringLiteral(".v64") } },
        { ID_SATURN, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso"), QStringLiteral(".chd") } },
        { ID_GBC, { QStringLiteral(".gbc") } },
        { ID_NEO_GEO, { QStringLiteral(".neo") } },
        { ID_TURBOGRAFX_CD, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".chd") } },
        { ID_SEGA_CD, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso"), QStringLiteral(".chd") } },
        { ID_PS2, { QStringLiteral(".iso"), QStringLiteral(".chd"), QStringLiteral(".cso"), QStringLiteral(".gz"), QStringLiteral(".elf"), QStringLiteral(".isz"), QStringLiteral(".bin"), QStringLiteral(".img"), QStringLiteral(".nrg") } },
        { ID_GAMECUBE, { QStringLiteral(".iso"), QStringLiteral(".gcm"), QStringLiteral(".gcz"), QStringLiteral(".rvz"), QStringLiteral(".cso"), QStringLiteral(".dol") } },
        { ID_DREAMCAST, { QStringLiteral(".cdi"), QStringLiteral(".gdi"), QStringLiteral(".chd"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".iso"), QStringLiteral(".dat"), QStringLiteral(".lst") } },
        { ID_GBA, { QStringLiteral(".gba"), QStringLiteral(".srl") } },
        { ID_LYNX, { QStringLiteral(".lnx"), QStringLiteral(".lyx") } },
        { ID_WII, { QStringLiteral(".iso"), QStringLiteral(".wbfs"), QStringLiteral(".rvz"), QStringLiteral(".gcz"), QStringLiteral(".cso"), QStringLiteral(".wad"), QStringLiteral(".dol") } },
        { ID_PSP, { QStringLiteral(".iso"), QStringLiteral(".cso"), QStringLiteral(".pbp"), QStringLiteral(".chd") } },
        { ID_NDS, { QStringLiteral(".nds"), QStringLiteral(".dsi"), QStringLiteral(".ids"), QStringLiteral(".srl"), QStringLiteral(".app") } },
        { ID_GAME_GEAR, { QStringLiteral(".gg") } },
        { ID_32X, { QStringLiteral(".32x") } },
        { ID_ATARI_JAGUAR, { QStringLiteral(".j64"), QStringLiteral(".jag") } },
        { ID_NGP, { QStringLiteral(".ngp"), QStringLiteral(".ngc") } },
        { ID_WONDERSWAN, { QStringLiteral(".ws"), QStringLiteral(".wsc") } },
        { ID_VIRTUAL_BOY, { QStringLiteral(".vb") } },
        { ID_3DS, { QStringLiteral(".3ds"), QStringLiteral(".cia"), QStringLiteral(".cci"), QStringLiteral(".3dz"), QStringLiteral(".cxi"), QStringLiteral(".app") } },
        { ID_SWITCH, { QStringLiteral(".nsp"), QStringLiteral(".xci"), QStringLiteral(".nsz"), QStringLiteral(".xcz") } },
        { ID_PSVITA, { QStringLiteral(".vpk") } },
        { ID_C64, { QStringLiteral(".d64"), QStringLiteral(".t64"), QStringLiteral(".tap"), QStringLiteral(".prg"), QStringLiteral(".crt"), QStringLiteral(".g64"), QStringLiteral(".p00"), QStringLiteral(".d71"), QStringLiteral(".d81") } },
        { ID_AMIGA, { QStringLiteral(".adf"), QStringLiteral(".adz"), QStringLiteral(".dms"), QStringLiteral(".ipf"), QStringLiteral(".hdf") } },
        { ID_ZX_SPECTRUM, { QStringLiteral(".z80"), QStringLiteral(".sna"), QStringLiteral(".szx"), QStringLiteral(".tap"), QStringLiteral(".tzx"), QStringLiteral(".dsk"), QStringLiteral(".trd"), QStringLiteral(".scl") } },
        { ID_SUPERGRAFX, { QStringLiteral(".sgx") } },
        { ID_XBOX, { QStringLiteral(".xiso"), QStringLiteral(".iso") } },
        { ID_XBOX360, { QStringLiteral(".xex"), QStringLiteral(".iso") } },
        { ID_ARCADE, { QStringLiteral(".zip") } },
        { ID_3DO, { QStringLiteral(".iso"), QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".chd") } },
        { ID_NEO_GEO_CD, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".chd"), QStringLiteral(".iso") } },
        { ID_COLECOVISION, { QStringLiteral(".col"), QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_INTELLIVISION, { QStringLiteral(".int"), QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_MSX, { QStringLiteral(".rom"), QStringLiteral(".mx1"), QStringLiteral(".dsk"), QStringLiteral(".cas"), QStringLiteral(".sg"), QStringLiteral(".sc"), QStringLiteral(".m2") } },
        { ID_MSX2, { QStringLiteral(".rom"), QStringLiteral(".mx2"), QStringLiteral(".dsk"), QStringLiteral(".cas") } },
        { ID_PC_FX, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso"), QStringLiteral(".chd") } },
        { ID_CDI, { QStringLiteral(".chd"), QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso") } },
        { ID_CD32, { QStringLiteral(".chd"), QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".iso") } },
        { ID_NAOMI, { QStringLiteral(".cue"), QStringLiteral(".bin"), QStringLiteral(".chd"), QStringLiteral(".gdi") } },
        { ID_SG1000, { QStringLiteral(".sg"), QStringLiteral(".sc"), QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_WIIU, { QStringLiteral(".wud"), QStringLiteral(".wux"), QStringLiteral(".rvz") } },
        { ID_PS3, { QStringLiteral(".iso"), QStringLiteral(".pkg") } },
        { ID_AMSTRAD_CPC, { QStringLiteral(".dsk"), QStringLiteral(".cdt"), QStringLiteral(".sna"), QStringLiteral(".tap"), QStringLiteral(".zip") } },
        { ID_ENTERPRISE_128, { QStringLiteral(".ep128"), QStringLiteral(".com"), QStringLiteral(".tap"), QStringLiteral(".cas") } },
        { ID_ZX81, { QStringLiteral(".p"), QStringLiteral(".tzx"), QStringLiteral(".t81") } },
        { ID_VIDEOTON_TVC, { QStringLiteral(".cas"), QStringLiteral(".dsk") } },
        { ID_SEGA_PICO, { QStringLiteral(".md"), QStringLiteral(".bin"), QStringLiteral(".smd") } },
        { ID_VIC20, { QStringLiteral(".prg"), QStringLiteral(".d64"), QStringLiteral(".tap"), QStringLiteral(".crt"), QStringLiteral(".t64") } },
        { ID_ODYSSEY2, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_SUPERVISION, { QStringLiteral(".sv") } },
        { ID_POCKET_CHALLENGE_V2, { QStringLiteral(".pc2"), QStringLiteral(".ws") } },
        { ID_PC98, { QStringLiteral(".hdi"), QStringLiteral(".fdi"), QStringLiteral(".hdm"), QStringLiteral(".d88"), QStringLiteral(".88d"), QStringLiteral(".nfd") } },
        { ID_INTERTON_VC4000, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_ARCADIA_2001, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_VECTREX, { QStringLiteral(".vec"), QStringLiteral(".bin"), QStringLiteral(".gam"), QStringLiteral(".rom") } },
        { ID_POKEMON_MINI, { QStringLiteral(".min"), QStringLiteral(".rom") } },
        { ID_CHANNEL_F, { QStringLiteral(".bin"), QStringLiteral(".chf"), QStringLiteral(".rom") } },
        { ID_SCV, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_GP32, { QStringLiteral(".gp32"), QStringLiteral(".fxe") } },
        { ID_GAMECOM, { QStringLiteral(".tgc"), QStringLiteral(".bin") } },
        { ID_STUDIO_II, { QStringLiteral(".bin"), QStringLiteral(".st2"), QStringLiteral(".rom") } },
        { ID_ATOMISWAVE, { QStringLiteral(".bin"), QStringLiteral(".zip") } },
        { ID_CASIO_PV1000, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_SUPER_ACAN, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_CASIO_LOOPY, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_SHARP_X1, { QStringLiteral(".d88"), QStringLiteral(".2d"), QStringLiteral(".tap"), QStringLiteral(".cas") } },
        { ID_X68000, { QStringLiteral(".dim"), QStringLiteral(".xdf"), QStringLiteral(".hdf"), QStringLiteral(".d88"), QStringLiteral(".m3u") } },
        { ID_IBM_PC, { QStringLiteral(".iso"), QStringLiteral(".img"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd"), QStringLiteral(".mdf") } },
        { ID_PS4, { QStringLiteral(".pkg"), QStringLiteral(".iso") } },
        { ID_XBOX_ONE, { QStringLiteral(".xvd"), QStringLiteral(".iso") } },
        { ID_MAC, { QStringLiteral(".toast"), QStringLiteral(".iso"), QStringLiteral(".img"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd") } },
        { ID_FM_TOWNS, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd"), QStringLiteral(".img") } },
        { ID_PC88, { QStringLiteral(".t88"), QStringLiteral(".n88"), QStringLiteral(".d88"), QStringLiteral(".88d") } },
        { ID_CDTV, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd") } },
        { ID_AMIGA_CD, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd") } },
        { ID_ARCHIMEDES, { QStringLiteral(".adf"), QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd") } },
        { ID_TRIFORCE, { QStringLiteral(".iso"), QStringLiteral(".gcm") } },
        { ID_CHIHIRO, { QStringLiteral(".iso") } },
        { ID_TANDY_VIS, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue") } },
        { ID_LINDBERGH, { QStringLiteral(".iso") } },
        { ID_PALM_OS, { QStringLiteral(".pdb"), QStringLiteral(".prc"), QStringLiteral(".pqa") } },
        { ID_PLAYDIA, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue"), QStringLiteral(".chd") } },
        { ID_APPLE_II, { QStringLiteral(".do"), QStringLiteral(".po"), QStringLiteral(".2mg"), QStringLiteral(".nib"), QStringLiteral(".woz"), QStringLiteral(".dsk"), QStringLiteral(".hdv") } },
        { ID_BBC_MICRO, { QStringLiteral(".ssd"), QStringLiteral(".dsd"), QStringLiteral(".uef"), QStringLiteral(".bbc"), QStringLiteral(".adl") } },
        { ID_C16, { QStringLiteral(".d16"), QStringLiteral(".prg"), QStringLiteral(".tap"), QStringLiteral(".t64") } },
        { ID_MEGA_DUCK, { QStringLiteral(".bin"), QStringLiteral(".md2") } },
        { ID_MICROVISION, { QStringLiteral(".bin"), QStringLiteral(".mvc") } },
        { ID_NUON, { QStringLiteral(".iso"), QStringLiteral(".bin"), QStringLiteral(".cue") } },
        { ID_VSMILE, { QStringLiteral(".bin"), QStringLiteral(".u1"), QStringLiteral(".u3") } },
        { ID_LEAPSTER, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_LEAPPAD, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_SEGA_BEENA, { QStringLiteral(".bin"), QStringLiteral(".md") } },
        { ID_CREATIVISION, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_PICNO, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_GAME_MASTER, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
        { ID_SYMBIAN, { QStringLiteral(".sis"), QStringLiteral(".sisx"), QStringLiteral(".app") } },
        { ID_ADVENTURE_VISION, { QStringLiteral(".bin"), QStringLiteral(".rom") } },
    };
    return kExtensions;
}

QStringList dbExtensionsForSystem(int systemId) {
    return systemDbExtensions().value(systemId);
}

} // namespace Systems
} // namespace Constants
} // namespace remustwo
