#include "system_resolver.h"
#include "constants/providers.h"

namespace remustwo {

using namespace Constants;
using namespace Constants::Providers;
using namespace Constants::Systems;

QMap<int, QMap<QString, QString>> SystemResolver::providerMappings() {
    // RetroAchievements system IDs are numeric strings verified against
    // API_GetConsoleIDs.php — https://retroachievements.org/API/API_GetConsoleIDs.php
    return {
        { ID_NES,
            { { THEGAMESDB, QStringLiteral("7") }, { SCREENSCRAPER, QStringLiteral("3") },
                { IGDB, QStringLiteral("nes") }, { RETROACHIEVEMENTS, QStringLiteral("7") },
                { WIKIDATA, QStringLiteral("Q172742") } } },
        { ID_SNES,
            { { THEGAMESDB, QStringLiteral("6") }, { SCREENSCRAPER, QStringLiteral("4") },
                { IGDB, QStringLiteral("snes") }, { RETROACHIEVEMENTS, QStringLiteral("3") },
                { WIKIDATA, QStringLiteral("Q170325") } } },
        { ID_N64,
            { { THEGAMESDB, QStringLiteral("3") }, { SCREENSCRAPER, QStringLiteral("14") },
                { IGDB, QStringLiteral("n64") }, { RETROACHIEVEMENTS, QStringLiteral("2") },
                { WIKIDATA, QStringLiteral("Q169983") } } },
        { ID_GAMECUBE,
            { { THEGAMESDB, QStringLiteral("2") }, { SCREENSCRAPER, QStringLiteral("13") },
                { IGDB, QStringLiteral("gamecube") }, { RETROACHIEVEMENTS, QStringLiteral("16") },
                { WIKIDATA, QStringLiteral("Q170336") } } },
        { ID_WII,
            { { THEGAMESDB, QStringLiteral("9") }, { SCREENSCRAPER, QStringLiteral("16") },
                { IGDB, QStringLiteral("wii") }, { RETROACHIEVEMENTS, QStringLiteral("20") },
                { WIKIDATA, QStringLiteral("Q170360") } } },
        { ID_GB,
            { { THEGAMESDB, QStringLiteral("4") }, { SCREENSCRAPER, QStringLiteral("9") },
                { IGDB, QStringLiteral("gameboy") }, { RETROACHIEVEMENTS, QStringLiteral("4") },
                { WIKIDATA, QStringLiteral("Q188642") } } },
        { ID_GBC,
            { { THEGAMESDB, QStringLiteral("41") }, { SCREENSCRAPER, QStringLiteral("10") },
                { IGDB, QStringLiteral("gbc") }, { RETROACHIEVEMENTS, QStringLiteral("6") },
                { WIKIDATA, QStringLiteral("Q183259") } } },
        { ID_GBA,
            { { THEGAMESDB, QStringLiteral("5") }, { SCREENSCRAPER, QStringLiteral("12") },
                { IGDB, QStringLiteral("gba") }, { RETROACHIEVEMENTS, QStringLiteral("5") },
                { WIKIDATA, QStringLiteral("Q188774") } } },
        { ID_NDS,
            { { THEGAMESDB, QStringLiteral("8") }, { SCREENSCRAPER, QStringLiteral("15") },
                { IGDB, QStringLiteral("nds") }, { RETROACHIEVEMENTS, QStringLiteral("18") },
                { WIKIDATA, QStringLiteral("Q170028") } } },
        { ID_3DS,
            { { THEGAMESDB, QStringLiteral("4912") }, { SCREENSCRAPER, QStringLiteral("17") },
                { IGDB, QStringLiteral("3ds") }, { RETROACHIEVEMENTS, QStringLiteral("62") },
                { WIKIDATA, QStringLiteral("Q170020") } } },
        { ID_SWITCH,
            { { THEGAMESDB, QStringLiteral("4971") }, { SCREENSCRAPER, QStringLiteral("225") },
                { IGDB, QStringLiteral("switch") }, { RETROACHIEVEMENTS, QStringLiteral("63") } } },
        { ID_VIRTUAL_BOY,
            { { THEGAMESDB, QStringLiteral("28") }, { SCREENSCRAPER, QStringLiteral("11") },
                { IGDB, QStringLiteral("virtualboy") }, { RETROACHIEVEMENTS, QStringLiteral("28") } } },
        { ID_GENESIS,
            { { THEGAMESDB, QStringLiteral("18") }, { SCREENSCRAPER, QStringLiteral("1") },
                { IGDB, QStringLiteral("genesis") }, { RETROACHIEVEMENTS, QStringLiteral("1") },
                { WIKIDATA, QStringLiteral("Q170624") } } },
        { ID_MASTER_SYSTEM,
            { { THEGAMESDB, QStringLiteral("35") }, { SCREENSCRAPER, QStringLiteral("2") },
                { IGDB, QStringLiteral("sms") }, { RETROACHIEVEMENTS, QStringLiteral("11") } } },
        { ID_GAME_GEAR,
            { { THEGAMESDB, QStringLiteral("20") }, { SCREENSCRAPER, QStringLiteral("8") },
                { IGDB, QStringLiteral("gamegear") }, { RETROACHIEVEMENTS, QStringLiteral("15") } } },
        { ID_SATURN,
            { { THEGAMESDB, QStringLiteral("17") }, { SCREENSCRAPER, QStringLiteral("22") },
                { IGDB, QStringLiteral("saturn") }, { RETROACHIEVEMENTS, QStringLiteral("39") } } },
        { ID_DREAMCAST,
            { { THEGAMESDB, QStringLiteral("16") }, { SCREENSCRAPER, QStringLiteral("23") },
                { IGDB, QStringLiteral("dreamcast") }, { RETROACHIEVEMENTS, QStringLiteral("40") } } },
        { ID_SEGA_CD,
            { { THEGAMESDB, QStringLiteral("21") }, { SCREENSCRAPER, QStringLiteral("20") },
                { IGDB, QStringLiteral("segacd") }, { RETROACHIEVEMENTS, QStringLiteral("9") } } },
        { ID_32X,
            { { THEGAMESDB, QStringLiteral("30") }, { SCREENSCRAPER, QStringLiteral("19") },
                { IGDB, QStringLiteral("sega32x") }, { RETROACHIEVEMENTS, QStringLiteral("10") } } },
        { ID_PSX,
            { { THEGAMESDB, QStringLiteral("10") }, { SCREENSCRAPER, QStringLiteral("57") },
                { IGDB, QStringLiteral("ps1") }, { RETROACHIEVEMENTS, QStringLiteral("12") },
                { WIKIDATA, QStringLiteral("Q170327") } } },
        { ID_PS2,
            { { THEGAMESDB, QStringLiteral("11") }, { SCREENSCRAPER, QStringLiteral("58") },
                { IGDB, QStringLiteral("ps2") }, { RETROACHIEVEMENTS, QStringLiteral("21") },
                { WIKIDATA, QStringLiteral("Q170388") } } },
        { ID_PSP,
            { { THEGAMESDB, QStringLiteral("13") }, { SCREENSCRAPER, QStringLiteral("61") },
                { IGDB, QStringLiteral("psp") }, { RETROACHIEVEMENTS, QStringLiteral("41") },
                { WIKIDATA, QStringLiteral("Q185723") } } },
        { ID_PSVITA,
            { { THEGAMESDB, QStringLiteral("39") }, { SCREENSCRAPER, QStringLiteral("62") },
                { IGDB, QStringLiteral("psvita") } } },
        { ID_ATARI_2600,
            { { THEGAMESDB, QStringLiteral("22") }, { SCREENSCRAPER, QStringLiteral("26") },
                { IGDB, QStringLiteral("atari2600") }, { RETROACHIEVEMENTS, QStringLiteral("25") } } },
        { ID_ATARI_7800,
            { { THEGAMESDB, QStringLiteral("28") }, { SCREENSCRAPER, QStringLiteral("27") },
                { IGDB, QStringLiteral("atari7800") }, { RETROACHIEVEMENTS, QStringLiteral("51") } } },
        { ID_LYNX,
            { { THEGAMESDB, QStringLiteral("25") }, { SCREENSCRAPER, QStringLiteral("28") },
                { IGDB, QStringLiteral("lynx") }, { RETROACHIEVEMENTS, QStringLiteral("13") } } },
        { ID_ATARI_JAGUAR,
            { { THEGAMESDB, QStringLiteral("27") }, { SCREENSCRAPER, QStringLiteral("29") },
                { IGDB, QStringLiteral("jaguar") }, { RETROACHIEVEMENTS, QStringLiteral("17") } } },
        { ID_TURBOGRAFX16,
            { { THEGAMESDB, QStringLiteral("31") }, { SCREENSCRAPER, QStringLiteral("31") },
                { IGDB, QStringLiteral("turbografx16") }, { RETROACHIEVEMENTS, QStringLiteral("8") } } },
        { ID_TURBOGRAFX_CD,
            { { THEGAMESDB, QStringLiteral("114") }, { SCREENSCRAPER, QStringLiteral("114") },
                { IGDB, QStringLiteral("turbografxcd") }, { RETROACHIEVEMENTS, QStringLiteral("76") } } },
        { ID_SUPERGRAFX,
            { { THEGAMESDB, QStringLiteral("105") }, { SCREENSCRAPER, QStringLiteral("105") },
                { IGDB, QStringLiteral("supergrafx") } } },
        { ID_NEO_GEO,
            { { THEGAMESDB, QStringLiteral("12") }, { SCREENSCRAPER, QStringLiteral("142") },
                { IGDB, QStringLiteral("neogeo") } } },
        { ID_NGP,
            { { THEGAMESDB, QStringLiteral("4911") }, { SCREENSCRAPER, QStringLiteral("25") },
                { IGDB, QStringLiteral("ngp") }, { RETROACHIEVEMENTS, QStringLiteral("14") } } },
        { ID_WONDERSWAN,
            { { THEGAMESDB, QStringLiteral("4923") }, { SCREENSCRAPER, QStringLiteral("45") },
                { IGDB, QStringLiteral("wonderswan") }, { RETROACHIEVEMENTS, QStringLiteral("53") } } },
        { ID_C64,
            { { THEGAMESDB, QStringLiteral("40") }, { SCREENSCRAPER, QStringLiteral("66") },
                { IGDB, QStringLiteral("c64") }, { WIKIDATA, QStringLiteral("Q172172") } } },
        { ID_AMIGA,
            { { THEGAMESDB, QStringLiteral("4916") }, { SCREENSCRAPER, QStringLiteral("64") },
                { IGDB, QStringLiteral("amiga") }, { WIKIDATA, QStringLiteral("Q100369") } } },
        { ID_IBM_PC,
            { { THEGAMESDB, QStringLiteral("1") }, { SCREENSCRAPER, QStringLiteral("135") },
                { IGDB, QStringLiteral("dos") }, { WIKIDATA, QStringLiteral("Q1661424") } } },
        { ID_ZX_SPECTRUM,
            { { THEGAMESDB, QStringLiteral("4918") }, { SCREENSCRAPER, QStringLiteral("76") },
                { IGDB, QStringLiteral("zxspectrum") }, { WIKIDATA, QStringLiteral("Q238642") } } },
        { ID_XBOX,
            { { THEGAMESDB, QStringLiteral("14") }, { SCREENSCRAPER, QStringLiteral("32") },
                { IGDB, QStringLiteral("xbox") } } },
        { ID_XBOX360,
            { { THEGAMESDB, QStringLiteral("15") }, { SCREENSCRAPER, QStringLiteral("33") },
                { IGDB, QStringLiteral("xbox360") }, { WIKIDATA, QStringLiteral("Q48263") } } },
        { ID_PS3, { { IGDB, QStringLiteral("ps3") }, { RETROACHIEVEMENTS, QStringLiteral("43") } } },
        { ID_WIIU, { { IGDB, QStringLiteral("wiiu") }, { RETROACHIEVEMENTS, QStringLiteral("38") } } },
        { ID_AMSTRAD_CPC, { { IGDB, QStringLiteral("cpc") }, { WIKIDATA, QStringLiteral("Q478829") } } },
        { ID_3DO, { { IGDB, QStringLiteral("3do") } } },
        { ID_NEO_GEO_CD, { { IGDB, QStringLiteral("neogeocd") } } },
        { ID_FDS, { { IGDB, QStringLiteral("fds") } } },
        { ID_ATARI_5200, { { IGDB, QStringLiteral("atari5200") } } },
        { ID_ATARI_8BIT, { { IGDB, QStringLiteral("atari8bit") } } },
        { ID_ATARI_ST, { { IGDB, QStringLiteral("atari-st") } } },
        { ID_COLECOVISION, { { IGDB, QStringLiteral("colecovision") } } },
        { ID_INTELLIVISION, { { IGDB, QStringLiteral("intellivision") } } },
        { ID_MSX, { { IGDB, QStringLiteral("msx") } } },
        { ID_MSX2, { { IGDB, QStringLiteral("msx2") } } },
        { ID_PC_FX, { { IGDB, QStringLiteral("pc-fx") } } },
        { ID_CDI, { { IGDB, QStringLiteral("philips-cdi") } } },
        { ID_CD32, { { IGDB, QStringLiteral("amiga-cd32") } } },
        { ID_VIC20, { { IGDB, QStringLiteral("vic-20") } } },
        { ID_ODYSSEY2, { { IGDB, QStringLiteral("odyssey-2") } } },
        { ID_PC98, { { IGDB, QStringLiteral("pc-98") } } },
        { ID_PS4, { { IGDB, QStringLiteral("ps4") } } },
        { ID_XBOX_ONE, { { IGDB, QStringLiteral("xbox-one") } } },
        { ID_SG1000, { { IGDB, QStringLiteral("sg-1000") } } },
    };
}

} // namespace remustwo
