#include "constants/systems.h"

namespace remustwo {
namespace Constants {
    namespace Systems {

        const QMap<QString, QList<int>> EXTENSION_TO_SYSTEMS = {
            { QStringLiteral(".nes"), { ID_NES } },
            { QStringLiteral(".nez"), { ID_NES } },
            { QStringLiteral(".unf"), { ID_NES } },
            { QStringLiteral(".unif"), { ID_NES } },
            { QStringLiteral(".fds"), { ID_FDS } },
            { QStringLiteral(".sfc"), { ID_SNES } },
            { QStringLiteral(".smc"), { ID_SNES } },
            { QStringLiteral(".n64"), { ID_N64 } },
            { QStringLiteral(".z64"), { ID_N64 } },
            { QStringLiteral(".v64"), { ID_N64 } },
            { QStringLiteral(".ndd"), { ID_N64 } },
            { QStringLiteral(".gb"), { ID_GB } },
            { QStringLiteral(".gbc"), { ID_GBC } },
            { QStringLiteral(".gba"), { ID_GBA } },
            { QStringLiteral(".srl"), { ID_GBA, ID_NDS } },
            { QStringLiteral(".nds"), { ID_NDS } },
            { QStringLiteral(".dsi"), { ID_NDS } },
            { QStringLiteral(".ids"), { ID_NDS } },
            { QStringLiteral(".gcm"), { ID_GAMECUBE } },
            { QStringLiteral(".gcz"), { ID_GAMECUBE, ID_WII } },
            { QStringLiteral(".rvz"), { ID_GAMECUBE, ID_WII } },
            { QStringLiteral(".wbfs"), { ID_WII } },
            { QStringLiteral(".wad"), { ID_WII } },
            { QStringLiteral(".dol"), { ID_GAMECUBE, ID_WII } },
            { QStringLiteral(".3ds"), { ID_3DS } },
            { QStringLiteral(".3dz"), { ID_3DS } },
            { QStringLiteral(".cia"), { ID_3DS } },
            { QStringLiteral(".cci"), { ID_3DS } },
            { QStringLiteral(".cxi"), { ID_3DS } },
            { QStringLiteral(".nsp"), { ID_SWITCH } },
            { QStringLiteral(".xci"), { ID_SWITCH } },
            { QStringLiteral(".nsz"), { ID_SWITCH } },
            { QStringLiteral(".xcz"), { ID_SWITCH } },
            { QStringLiteral(".vb"), { ID_VIRTUAL_BOY } },
            { QStringLiteral(".sms"), { ID_MASTER_SYSTEM } },
            { QStringLiteral(".gg"), { ID_GAME_GEAR } },
            { QStringLiteral(".md"), { ID_GENESIS } },
            { QStringLiteral(".gen"), { ID_GENESIS } },
            { QStringLiteral(".smd"), { ID_GENESIS } },
            { QStringLiteral(".32x"), { ID_32X } },
            { QStringLiteral(".68k"), { ID_GENESIS } },
            { QStringLiteral(".cdi"), { ID_DREAMCAST } },
            { QStringLiteral(".gdi"), { ID_DREAMCAST } },
            { QStringLiteral(".pbp"), { ID_PSX, ID_PSP } },
            { QStringLiteral(".ecm"), { ID_PSX } },
            { QStringLiteral(".mdf"), { ID_PSX, ID_PS2 } },
            { QStringLiteral(".mds"), { ID_PSX, ID_PS2 } },
            { QStringLiteral(".ccd"), { ID_PSX, ID_PS2 } },
            { QStringLiteral(".sub"), { ID_PSX } },
            { QStringLiteral(".cso"), { ID_PSP, ID_PS2, ID_GAMECUBE, ID_WII } },
            { QStringLiteral(".vpk"), { ID_PSVITA } },
            { QStringLiteral(".a26"), { ID_ATARI_2600 } },
            { QStringLiteral(".a78"), { ID_ATARI_7800 } },
            { QStringLiteral(".lnx"), { ID_LYNX } },
            { QStringLiteral(".lyx"), { ID_LYNX } },
            { QStringLiteral(".j64"), { ID_ATARI_JAGUAR } },
            { QStringLiteral(".jag"), { ID_ATARI_JAGUAR } },
            { QStringLiteral(".pce"), { ID_TURBOGRAFX16 } },
            { QStringLiteral(".sgx"), { ID_SUPERGRAFX } },
            { QStringLiteral(".neo"), { ID_NEO_GEO } },
            { QStringLiteral(".ngp"), { ID_NGP } },
            { QStringLiteral(".ngc"), { ID_NGP } },
            { QStringLiteral(".ws"), { ID_WONDERSWAN } },
            { QStringLiteral(".wsc"), { ID_WONDERSWAN } },
            { QStringLiteral(".xiso"), { ID_XBOX } },
            { QStringLiteral(".xex"), { ID_XBOX360 } },
            { QStringLiteral(".xbe"), { ID_XBOX } },
            { QStringLiteral(".d64"), { ID_C64 } },
            { QStringLiteral(".d71"), { ID_C64 } },
            { QStringLiteral(".d81"), { ID_C64 } },
            { QStringLiteral(".t64"), { ID_C64 } },
            { QStringLiteral(".prg"), { ID_C64 } },
            { QStringLiteral(".p00"), { ID_C64 } },
            { QStringLiteral(".crt"), { ID_C64 } },
            { QStringLiteral(".g64"), { ID_C64 } },
            { QStringLiteral(".adf"), { ID_AMIGA, ID_ARCHIMEDES } },
            { QStringLiteral(".adz"), { ID_AMIGA } },
            { QStringLiteral(".dms"), { ID_AMIGA } },
            { QStringLiteral(".ipf"), { ID_AMIGA } },
            { QStringLiteral(".hdf"), { ID_AMIGA } },
            { QStringLiteral(".z80"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".sna"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".szx"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".tzx"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".pzx"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".trd"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".scl"), { ID_ZX_SPECTRUM } },
            { QStringLiteral(".iso"),
                { ID_PSX, ID_PS2, ID_GAMECUBE, ID_WII, ID_PSP, ID_SATURN, ID_SEGA_CD, ID_DREAMCAST, ID_XBOX, ID_XBOX360,
                    ID_3DO, ID_NEO_GEO_CD, ID_IBM_PC, ID_PS4, ID_XBOX_ONE, ID_MAC, ID_FM_TOWNS, ID_CDTV, ID_AMIGA_CD,
                    ID_ARCHIMEDES, ID_TRIFORCE, ID_CHIHIRO, ID_TANDY_VIS, ID_LINDBERGH, ID_PLAYDIA, ID_NUON } },
            { QStringLiteral(".cue"),
                { ID_PSX, ID_SATURN, ID_SEGA_CD, ID_TURBOGRAFX_CD, ID_DREAMCAST, ID_PS2, ID_3DO, ID_NEO_GEO_CD,
                    ID_IBM_PC, ID_FM_TOWNS, ID_CDTV, ID_AMIGA_CD, ID_ARCHIMEDES, ID_TANDY_VIS, ID_PLAYDIA, ID_NUON } },
            { QStringLiteral(".bin"),
                { ID_PSX, ID_SATURN, ID_SEGA_CD, ID_TURBOGRAFX_CD, ID_ATARI_2600, ID_DREAMCAST, ID_PS2, ID_GENESIS,
                    ID_3DO, ID_NEO_GEO_CD, ID_IBM_PC, ID_FM_TOWNS, ID_CDTV, ID_AMIGA_CD, ID_TANDY_VIS, ID_PLAYDIA,
                    ID_NUON, ID_MEGA_DUCK, ID_MICROVISION } },
            { QStringLiteral(".chd"),
                { ID_PSX, ID_PS2, ID_SATURN, ID_SEGA_CD, ID_TURBOGRAFX_CD, ID_DREAMCAST, ID_PSP, ID_3DO, ID_NEO_GEO_CD,
                    ID_IBM_PC, ID_FM_TOWNS, ID_CDTV, ID_AMIGA_CD, ID_ARCHIMEDES, ID_PLAYDIA } },
            { QStringLiteral(".img"), { ID_PSX, ID_PS2, ID_SATURN, ID_IBM_PC, ID_MAC, ID_FM_TOWNS } },
            { QStringLiteral(".m3u"), { ID_PSX, ID_PS2, ID_SATURN, ID_SEGA_CD, ID_DREAMCAST, ID_FM_TOWNS, ID_IBM_PC } },
            { QStringLiteral(".tap"), { ID_C64, ID_ZX_SPECTRUM } },
            { QStringLiteral(".dsk"),
                { ID_ZX_SPECTRUM, ID_AMIGA, ID_AMSTRAD_CPC, ID_MSX, ID_MSX2, ID_SHARP_X1, ID_X68000, ID_VIDEOTON_TVC,
                    ID_APPLE_II, ID_BBC_MICRO, ID_C16 } },
            { QStringLiteral(".elf"), { ID_PS2, ID_GAMECUBE, ID_WII } },
            { QStringLiteral(".nrg"), { ID_PSX, ID_PS2 } },
            { QStringLiteral(".isz"), { ID_PS2 } },
            { QStringLiteral(".app"), { ID_NDS, ID_3DS } },
            // 3DO and Neo Geo CD disc formats
            { QStringLiteral(".3do"), { ID_3DO } },
            // New systems (IDs 58-82)
            { QStringLiteral(".cdt"), { ID_AMSTRAD_CPC } },
            { QStringLiteral(".ep128"), { ID_ENTERPRISE_128 } },
            { QStringLiteral(".p"), { ID_ZX81 } },
            { QStringLiteral(".t81"), { ID_ZX81 } },
            { QStringLiteral(".sv"), { ID_SUPERVISION } },
            { QStringLiteral(".pc2"), { ID_POCKET_CHALLENGE_V2 } },
            { QStringLiteral(".hdi"), { ID_PC98 } },
            { QStringLiteral(".fdi"), { ID_PC98 } },
            { QStringLiteral(".hdm"), { ID_PC98 } },
            { QStringLiteral(".d88"), { ID_PC98, ID_SHARP_X1, ID_X68000, ID_PC88 } },
            { QStringLiteral(".88d"), { ID_PC98 } },
            { QStringLiteral(".nfd"), { ID_PC98 } },
            { QStringLiteral(".vec"), { ID_VECTREX } },
            { QStringLiteral(".gam"), { ID_VECTREX } },
            { QStringLiteral(".min"), { ID_POKEMON_MINI } },
            { QStringLiteral(".chf"), { ID_CHANNEL_F } },
            { QStringLiteral(".gp32"), { ID_GP32 } },
            { QStringLiteral(".fxe"), { ID_GP32 } },
            { QStringLiteral(".tgc"), { ID_GAMECOM } },
            { QStringLiteral(".st2"), { ID_STUDIO_II } },
            { QStringLiteral(".xdf"), { ID_X68000 } },
            { QStringLiteral(".dim"), { ID_ATARI_ST, ID_X68000 } },
            { QStringLiteral(".2d"), { ID_SHARP_X1 } },
            // New system extensions (IDs 83-103)
            { QStringLiteral(".pkg"), { ID_PS4 } },
            { QStringLiteral(".xvd"), { ID_XBOX_ONE } },
            { QStringLiteral(".toast"), { ID_MAC } },
            { QStringLiteral(".t88"), { ID_PC88 } },
            { QStringLiteral(".n88"), { ID_PC88 } },
            { QStringLiteral(".pdb"), { ID_PALM_OS } },
            { QStringLiteral(".prc"), { ID_PALM_OS } },
            { QStringLiteral(".pqa"), { ID_PALM_OS } },
            { QStringLiteral(".do"), { ID_APPLE_II } },
            { QStringLiteral(".po"), { ID_APPLE_II } },
            { QStringLiteral(".2mg"), { ID_APPLE_II } },
            { QStringLiteral(".nib"), { ID_APPLE_II } },
            { QStringLiteral(".woz"), { ID_APPLE_II } },
            { QStringLiteral(".hdv"), { ID_APPLE_II } },
            { QStringLiteral(".ssd"), { ID_BBC_MICRO } },
            { QStringLiteral(".dsd"), { ID_BBC_MICRO } },
            { QStringLiteral(".uef"), { ID_BBC_MICRO } },
            { QStringLiteral(".bbc"), { ID_BBC_MICRO } },
            { QStringLiteral(".adl"), { ID_BBC_MICRO } },
            { QStringLiteral(".d16"), { ID_C16 } },
            { QStringLiteral(".md2"), { ID_MEGA_DUCK } },
            { QStringLiteral(".mvc"), { ID_MICROVISION } },
        };

    } // namespace Systems
} // namespace Constants
} // namespace remustwo
